name: Hello world workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: hello world
        runs: echo "hello world"
        shell: bash

  Goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Goodbye world
        runs: echo "Goodbye world"
        shell: bash
