name: Hello world workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: hello world name
        run: echo "hello world value"
        shell: bash

  Goodbye:
    runs-on: ubuntu-latest
    needs: Hello
    steps:
      - name: Goodbye world name
        run: echo "Goodbye world value"
        shell: bash
