name: Manual workflow

on:
  workflow_dispach:
    inputs:
      name:
        description: 'Name'
        type: string 
        default: 'test'
      age:
        description: 'Age'
        type: number
        require: true

jobs: 
  Manual:
    runs-on: ubuntu-latest